#!/usr/bin/env sh

# Load and reload Yabai
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Behavior
yabai -m config layout               bsp
yabai -m config window_placement     second_child
yabai -m config split_ratio          0.50
yabai -m config mouse_follows_focus  on
yabai -m config focus_follows_mouse  autoraise
yabai -m config window_topmost       on

# Visuals
yabai -m config window_border        off
yabai -m config window_shadow        float
yabai -m config top_padding          0
yabai -m config bottom_padding       0
yabai -m config left_padding         0
yabai -m config right_padding        0
yabai -m config window_gap           0

# Activated by skhd in resize mode.
yabai -m config active_window_border_color 0xff0f75b1

# Rules
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app='^GIMP' title!='(^GNU|GIMP$)' manage=off
yabai -m rule --add app='Python' manage=off

# Signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
