live_config_reload = true

[colors.bright]
black = "#1f1f1f"
blue = "#81a1d5"
cyan = "#94d3d6"
green = "#85a385"
magenta = "#9292bf"
red = "#d09a9a"
white = "#dcdccc"
yellow = "#e6d3b3"

[colors.cursor]
cursor = "#adada2"
text = "#3a3a3a"

[colors.normal]
# black = "#1f1f1f"
black = "#222222"
blue = "#799bd2"
cyan = "#8cd0d3"
green = "#7f9f7f"
magenta = "#8c8cbc"
red = "#cc9393"
white = "#adada2"
yellow = "#e3ceab"

[colors.primary]
background = "#3a3a3a"
foreground = "#adada2"

[colors.vi_mode_cursor]
cursor = "#adada2"
text = "#3a3a3a"

[env]
TERM = "xterm-256color"

[font]
# family = "DejaVu Sans Mono"
size = 15.0

[font.offset]
x = 1
y = 0

[scrolling]
multiplier = 5

[window]
decorations = "Buttonless"

[keyboard]
bindings = [

  # Forward CMD to CTRL
  { key = "At", mods = "Super", chars = "\u0000" },
  { key = "A", mods = "Super", chars = "\u0001" },
  { key = "B", mods = "Super", chars = "\u0002" },
  { key = "C", mods = "Super", chars = "\u0003" },
  { key = "D", mods = "Super", chars = "\u0004" },
  { key = "E", mods = "Super", chars = "\u0005" },
  { key = "F", mods = "Super", chars = "\u0006" },
  { key = "G", mods = "Super", chars = "\u0007" },
  { key = "H", mods = "Super", chars = "\u0008" },
  { key = "I", mods = "Super", chars = "\u0009" },
  { key = "J", mods = "Super", chars = "\u000a" },
  { key = "K", mods = "Super", chars = "\u000b" },
  { key = "L", mods = "Super", chars = "\u000c" },
  { key = "M", mods = "Super", chars = "\u000d" },
  { key = "N", mods = "Super", chars = "\u000e" },
  { key = "O", mods = "Super", chars = "\u000f" },
  { key = "P", mods = "Super", chars = "\u0010" },
  { key = "Q", mods = "Super", chars = "\u0011" },
  { key = "R", mods = "Super", chars = "\u0012" },
  { key = "S", mods = "Super", chars = "\u0013" },
  { key = "T", mods = "Super", chars = "\u0014" },
  { key = "U", mods = "Super", chars = "\u0015" },
  { key = "V", mods = "Super", chars = "\u0016" },
  { key = "W", mods = "Super", chars = "\u0017" },
  { key = "X", mods = "Super", chars = "\u0018" },
  { key = "Y", mods = "Super", chars = "\u0019" },
  { key = "Z", mods = "Super", chars = "\u001a" },
  { key = "LBracket", mods = "Super", chars = "\u001b" },
  { key = "Backslash", mods = "Super", chars = "\u001c" },
  { key = "RBracket", mods = "Super", chars = "\u001d" },
  { key = "`", mods = "Super", chars = "\u001e" },
  { key = "_", mods = "Super", chars = "\u001f" },

  # # Unbind default CTRL shortcuts
  # { key = "At", mods = "Control", chars = "@" },
  # { key = "A", mods = "Control", chars = "a" },
  # { key = "B", mods = "Control", chars = "b" },
  # { key = "C", mods = "Control", action = "Copy" },
  # { key = "D", mods = "Control", chars = "d" },
  # { key = "E", mods = "Control", chars = "e" },
  # { key = "G", mods = "Control", chars = "g" },
  # { key = "H", mods = "Control", chars = "h" },
  # { key = "I", mods = "Control", chars = "i" },
  # { key = "J", mods = "Control", chars = "j" },
  # { key = "K", mods = "Control", chars = "k" },
  # { key = "L", mods = "Control", chars = "l" },
  # { key = "M", mods = "Control", chars = "m" },
  # { key = "N", mods = "Control", action = "CreateNewWindow" },
  # { key = "O", mods = "Control", chars = "o" },
  # { key = "P", mods = "Control", chars = "p" },
  # { key = "Q", mods = "Control", action = "Quit" },
  # { key = "R", mods = "Control", chars = "r" },
  # { key = "S", mods = "Control", chars = "s" },
  # { key = "T", mods = "Control", chars = "t" },
  # { key = "U", mods = "Control", chars = "u" },
  # { key = "V", mods = "Control", action = "Paste" },
  # { key = "W", mods = "Control", action = "Quit" },
  # { key = "X", mods = "Control", chars = "Cut" },
  # { key = "Y", mods = "Control", chars = "y" },
  # { key = "Z", mods = "Control", chars = "z" },
  # { key = "LBracket", mods = "Control", chars = "[" },
  # { key = "Backslash", mods = "Control", chars = "\\" },
  # { key = "RBracket", mods = "Control", chars = "]" },
  # { key = "`", mods = "Control", chars = "`" },
  # { key = "_", mods = "Control", chars = "_" },

  # Use CTRL for most MacOS bindings
  { key = "C", mods = "Control", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" },
  { key = "Q", mods = "Control", action = "Quit" },
  { key = "N", mods = "Control", action = "CreateNewWindow" },
  { key = "Enter", mods = "Control", action = "ToggleViMode" },
  { key = "Q", mode = "Vi", action = "ToggleViMode" },

  # Somehow CTRL+Plus cannot be bound so we use CMD for these
  { key = "+", mods = "Super", action = "IncreaseFontSize" },
  { key = "-", mods = "Super", action = "DecreaseFontSize" },
  { key = "0", mods = "Super", action = "ResetFontSize" },

]

