live_config_reload = true

[colors.bright]
black = "#7e7f78"
blue = "#81a1d5"
cyan = "#94d3d6"
green = "#85a385"
magenta = "#9292bf"
red = "#d09a9a"
white = "#dcdccc"
yellow = "#e6d3b3"

[colors.cursor]
cursor = "#adada2"
text = "#3a3a3a"

[colors.normal]
black = "#1f1f1f"
blue = "#799bd2"
cyan = "#8cd0d3"
green = "#7f9f7f"
magenta = "#8c8cbc"
red = "#cc9393"
white = "#adada2"
yellow = "#e3ceab"

[colors.primary]
background = "#3a3a3a"
foreground = "#adada2"

[colors.vi_mode_cursor]
cursor = "#adada2"
text = "#3a3a3a"

[env]
TERM = "xterm-256color"

[font]
# family = "DejaVu Sans Mono"
size = 15.0

[font.offset]
x = 1
y = 0

[scrolling]
multiplier = 5

[window]
decorations = "Buttonless"

[keyboard]
bindings = [

  # Use CTRL for MacOS bindings
  { key = "C", mods = "Control", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" },
  { key = "Q", mods = "Control", action = "Quit" },
  { key = "N", mods = "Control", action = "CreateNewWindow" },

  # Forward CMD to CTRL
  { key = "At", mods = "Super", chars = "\u0000" },
  { key = "A", mods = "Super", chars = "\u0001" },
  { key = "B", mods = "Super", chars = "\u0002" },
  { key = "C", mods = "Super", chars = "\u0003" },
  { key = "D", mods = "Super", chars = "\u0004" },
  { key = "E", mods = "Super", chars = "\u0005" },
  { key = "F", mods = "Super", chars = "\u0006" },
  { key = "G", mods = "Super", chars = "\u0007" },
  { key = "H", mods = "Super", chars = "\u0008" },
  { key = "I", mods = "Super", chars = "\u0009" },
  { key = "J", mods = "Super", chars = "\u000a" },
  { key = "K", mods = "Super", chars = "\u000b" },
  { key = "L", mods = "Super", chars = "\u000c" },
  { key = "M", mods = "Super", chars = "\u000d" },
  { key = "N", mods = "Super", chars = "\u000e" },
  { key = "O", mods = "Super", chars = "\u000f" },
  { key = "P", mods = "Super", chars = "\u0010" },
  { key = "Q", mods = "Super", chars = "\u0011" },
  { key = "R", mods = "Super", chars = "\u0012" },
  { key = "S", mods = "Super", chars = "\u0013" },
  { key = "T", mods = "Super", chars = "\u0014" },
  { key = "U", mods = "Super", chars = "\u0015" },
  { key = "V", mods = "Super", chars = "\u0016" },
  { key = "W", mods = "Super", chars = "\u0017" },
  { key = "X", mods = "Super", chars = "\u0018" },
  { key = "Y", mods = "Super", chars = "\u0019" },
  { key = "Z", mods = "Super", chars = "\u001a" },
  { key = "LBracket", mods = "Super", chars = "\u001b" },
  { key = "Backslash", mods = "Super", chars = "\u001c" },
  { key = "RBracket", mods = "Super", chars = "\u001d" },
  { key = "`", mods = "Super", chars = "\u001e" },
  { key = "_", mods = "Super", chars = "\u001f" },

]

