#!/bin/sh

. ~/autoload/path_variable

# List and edit directories.
alias l='command ls --color=auto --group-directories-first'
alias ls='l -lhA --time-style long-iso'
alias ll='tree -aL 2'
ed() {
  if [ -z "$1" ]; then; 1=$PWD; fi
  ~/bin/edit_list \
      --content-cmd "find $1" \
      --rename-cmd 'mv {} {}' \
      --delete-cmd 'rm -rf {}'
}

# Resolve aliases for sudo.
alias sudo='sudo '

# Git.
alias gs='git status'
alias gl='git log'
alias ga='git add -A'
alias gc='git commit -m '
alias gd='git diff HEAD'
alias gdc='git diff --cached'
gr() { git rebase -i HEAD~$1 }

# Mercurial.
alias hs='hg status'
alias hd='hg diff'
alias ha='hg addremove'
alias hc='hg commit -m '
alias hl='hg log'

# Python.
alias py='python3'
alias np='ipython -i -c " \
  import functools, itertools, pathlib, re; \
  import numpy as np; \
  import matplotlib.pyplot as plt; \
  import scipy.stats; \
  import gym; \
  random = np.random.RandomState(seed=0);"'
alias tf='nogpu ipython -i -c " \
  import functools, itertools, os, shutil; \
  import numpy as np; \
  import matplotlib.pyplot as plt; \
  import tensorflow as tf; \
  import tensorflow_probability as tfp; \
  from tensorflow_probability import distributions as tfd; \
  import gym; \
  random = np.random.RandomState(seed=0);"'
alias pytc='LD_PRELOAD=/usr/lib/libtcmalloc.so python3 -O'
alias pypdb='python3 -m pdb -c continue'
alias pyprof='python3 -m cProfile -s cumulative'  # Use as pyprof script.py > profile.txt

# Other.
alias nogpu='export CUDA_VISIBLE_DEVICES=-1;'
alias clip='xclip -selection c'
alias dark='xbacklight -set 0'
make_nice() {
  renice -n 20 -p $(pgrep $1)
}

# Fuzzy searches.
alias v="
  find $PWD | fzf --bind 'return:execute(vim {1} < /dev/tty)+abort' \
    --preview '(highlight -O ansi -l {} || head -100 {}) 2> /dev/null | head -100'"
alias ap="
  apt-cache search '.*' | grep -Eo '^[^ ]+' | \
  fzf --bind 'return:execute(sudo apt-get install {})+abort' \
  --preview 'apt-cache show {}'"
