#!/bin/sh

. ~/autoload/path_variable

# List directories.
alias l='command ls --color=auto --group-directories-first'
alias ls='l -lhA --time-style long-iso'
alias ll='tree -aL 2'

# Git.
alias gs='git status'
alias gl='git log'
alias ga='git add -A'
alias gc='git commit -m '
alias go='git checkout'
alias gb='git branch'
alias gd='git diff'
alias gdc='git diff --cached'
alias ge='git diff --name-only | uniq | xargs vim -p'
gr() {
  git rebase -i HEAD~$1
}

# Python.
alias p='python'
alias np='ipython -i -c " \
  import numpy as np; \
  import matplotlib; matplotlib.use(\"Agg\"); \
  import matplotlib.pyplot as plt; \
  import gym"'
alias tf='ipython -i -c " \
  import numpy as np; \
  import matplotlib; matplotlib.use(\"Agg\"); \
  import matplotlib.pyplot as plt; \
  import tensorflow as tf; \
  import gym"'
alias tc='LD_PRELOAD=/usr/lib/libtcmalloc.so python -O'
alias pi='sudo pip install'
alias pu='sudo pip uninstall'

# Cleanup.
alias clean-cmake='rm CMakeCache.txt && rm -rf CMakeFiles'
alias clean-symlinks='find -xtype l -delete'

# Other.
alias mk='mkdir'
alias pm='sudo pacman -S'
alias ya='yaourt'
alias pg='ping 8.8.8.8'
alias clip='xclip -selection c'
alias wifi='nmtui'
mknice() {
  renice -n 20 -p $(pgrep $1)
}
