#!/bin/sh

. ~/autoload/path_variable

# List directories.
alias l='command ls --color=auto --group-directories-first'
alias ls='l -lhA --time-style long-iso'
alias ll='tree -aL 2'

# Resolve aliases for sudo.
alias sudo='sudo '

# Git.
alias gs='git status'
alias gl='git log'
alias ga='git add -A'
alias gc='git commit -m '
alias go='git checkout'
alias gb='git branch'
alias gd='git diff'
alias gdc='git diff --cached'
alias ge='git diff --name-only | uniq | xargs vim -p'
gr() {
  git rebase -i HEAD~$1
}

# Python.
alias p='python'
alias np='ipython -i -c " \
  import functools, itertools, os, shutil; \
  import numpy as np; \
  import matplotlib.pyplot as plt; \
  import scipy.stats; \
  import gym"'
alias tf='nogpu ipython -i -c " \
  import functools, itertools, os, shutil; \
  import numpy as np; \
  import matplotlib.pyplot as plt; \
  import tensorflow as tf; \
  import gym; \
  tfd = tf.contrib.distributions; \
  sess = tf.InteractiveSession();"'
alias tc='LD_PRELOAD=/usr/lib/libtcmalloc.so python3 -O'
alias nogpu='export CUDA_VISIBLE_DEVICES=-1;'
alias pd='python -m pdb -c continue'

# Cleanup.
alias clean-cmake='rm CMakeCache.txt && rm -rf CMakeFiles'
alias clean-symlinks='find -xtype l -delete'

# Other.
alias mk='mkdir -p'
alias pm='sudo pacman -S'
alias ya='yaourt'
alias pg='ping 8.8.8.8'
alias clip='xclip -selection c'
alias wifi='nmtui'
alias dark='xbacklight -set 0'
mknice() {
  renice -n 20 -p $(pgrep $1)
}

# Fuzzy searches.
alias v="
  find $PWD | fzf --bind 'return:execute(vim {1} < /dev/tty)+abort' \
    --preview '(highlight -O ansi -l {} || head -100 {}) 2> /dev/null | head -100'"
alias ap="
  apt-cache search '.*' | grep -Eo '^[^ ]+' | \
  fzf --bind 'return:execute(sudo apt-get install {})+abort' \
  --preview 'apt-cache show {}'"
