#!/bin/zsh

function git_sync_status() {
    [[ -d '.git' ]] || return
    [[ -x "$(command -v git)" ]] || return
    git fetch --all > /dev/null || return

    LOCAL=$(git rev-parse @)
    REMOTE=$(git rev-parse @{u})
    BASE=$(git merge-base @ @{u})

    echo -n "Git: ${PWD##*/} "
    if [ $LOCAL = $REMOTE ]; then
        echo 'is up to date'
    elif [ $LOCAL = $BASE ]; then
        echo 'is behind'
    elif [ $REMOTE = $BASE ]; then
        echo 'is ahead'
    else
        echo 'has diverged'
    fi
}
